version: '3.6'

services:
  db:
    build: .
    container_name: mssql
    restart: always
    tty: true
    user: root
    ports:
      - ${DB_PORT}:1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./init.sql:/scripts/init.sql
    entrypoint: sh -c "sleep 5s && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P ${DB_PASS} -d master -i scripts/init.sql & /opt/mssql/bin/sqlservr"

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASS}
    extra_hosts:
      - "host.docker.internal:172.17.0.1"