version: '3.6'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    extra_hosts:
      - "host.docker.internal:172.17.0.1"